// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockQuoteChat.Infrastructure;

#nullable disable

namespace StockQuoteChat.Infrastructure.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockQuoteChat.Application.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoomId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("StockQuoteChat.Application.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3913a673-5f6b-4177-938f-3d83516482d7"),
                            Name = "Room One"
                        },
                        new
                        {
                            Id = new Guid("070344f1-018a-4443-8732-0a87ec7a5aa7"),
                            Name = "Room Two"
                        });
                });

            modelBuilder.Entity("StockQuoteChat.Application.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ae683b2-cdad-40c9-be04-34792ae196e3"),
                            Email = "userone@email.com",
                            FirstName = "ChatUserOne",
                            IsBot = false,
                            LastName = "",
                            Password = "123"
                        },
                        new
                        {
                            Id = new Guid("c8233f80-bc22-4886-9f26-64878f554da8"),
                            Email = "usertwo@email.com",
                            FirstName = "ChatUserTwo",
                            IsBot = false,
                            LastName = "",
                            Password = "123"
                        },
                        new
                        {
                            Id = new Guid("98085ba7-b79a-4d54-b857-9a7aa302bf19"),
                            Email = "mychatbot@chatmail.com",
                            FirstName = "Bot",
                            IsBot = true,
                            LastName = "",
                            Password = "botexamplepassword"
                        });
                });

            modelBuilder.Entity("StockQuoteChat.Application.Entities.UserRoom", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("UserRooms");
                });

            modelBuilder.Entity("StockQuoteChat.Application.Entities.Message", b =>
                {
                    b.HasOne("StockQuoteChat.Application.Entities.UserRoom", "UserRoom")
                        .WithMany("Messages")
                        .HasForeignKey("UserId", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRoom");
                });

            modelBuilder.Entity("StockQuoteChat.Application.Entities.UserRoom", b =>
                {
                    b.HasOne("StockQuoteChat.Application.Entities.Room", "Room")
                        .WithMany("UserRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockQuoteChat.Application.Entities.User", "User")
                        .WithMany("UserRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockQuoteChat.Application.Entities.Room", b =>
                {
                    b.Navigation("UserRooms");
                });

            modelBuilder.Entity("StockQuoteChat.Application.Entities.User", b =>
                {
                    b.Navigation("UserRooms");
                });

            modelBuilder.Entity("StockQuoteChat.Application.Entities.UserRoom", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
